#!/usr/bin/env python3
"""Generate per-release asset key material -> src/framework/core/keymaterial.gen.h

The asset master key protects the encrypted client assets (see ResourceManager
encryptBuffer/decryptBuffer). The C++ side DERIVES the real 32-byte key from the
material in this header via HKDF-SHA256, so this script only needs to emit random
bytes -- the key itself is never written anywhere.

Why per-release:
  - The generated header is GITIGNORED: the key never lands in version control.
  - Regenerate it for EVERY release. A leaked/cracked build then only exposes one
    version's key; the updater ships the next build with a fresh key.

Usage:
    python tools/gen_asset_key.py            # generate a fresh random key header
    python tools/gen_asset_key.py --force    # overwrite an existing header

Honesty note: this is obfuscation, not a vault. The material lives in the binary
because the client must decrypt its own assets. It raises the cost of a manual
reverse-engineer; it does not make extraction impossible.
"""
import os
import sys
import pathlib


def fmt(arr):
    return ", ".join(f"0x{b:02x}" for b in arr)


def main():
    force = "--force" in sys.argv[1:]
    here = pathlib.Path(__file__).resolve().parent
    out = here.parent / "src" / "framework" / "core" / "keymaterial.gen.h"

    if out.exists() and not force:
        print(f"refusing to overwrite existing {out} (use --force)")
        return 1

    a = os.urandom(12)
    b = os.urandom(12)
    c = os.urandom(12)
    salt = int.from_bytes(os.urandom(4), "little")

    text = (
        "#pragma once\n"
        "// AUTO-GENERATED by tools/gen_asset_key.py -- DO NOT COMMIT (gitignored).\n"
        "// Per-release asset master-key material. Regenerate for every release.\n"
        f"static const unsigned char NYXOS_KM_A[12] = {{ {fmt(a)} }};\n"
        f"static const unsigned char NYXOS_KM_B[12] = {{ {fmt(b)} }};\n"
        f"static const unsigned char NYXOS_KM_C[12] = {{ {fmt(c)} }};\n"
        f"static const unsigned int  NYXOS_KM_SALT = 0x{salt:08x}u;\n"
    )
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out}")
    print("Reminder: this file is gitignored. Keep the matching build's symbols/key")
    print("archived privately so you can reproduce/decrypt that release if needed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
